### ISSUE TITLE
Mismatching components somewhere?

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#205]
I'm not quite sure where yet, but I think there may be mismatching components in some glyph, between the 24 masters of the full font. I'm getting the following error from FontMake:

`AssertionError: (('dotaccentcomb', ('dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'cedillacomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'cedillacomb', 'dotaccentcomb', 'cedillacomb', 'dotaccentcomb', 'cedillacomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb')), 'str', '[0]', 'list', '.glyphs', 'Coverage', '[0]', 'list', '.Coverage', 'MarkGlyphSetsDef', '.MarkGlyphSetsDef', 'GDEF', '.table', 'table_G_D_E_F_')`

It seems that probably, there are 4 sources that use `cedillacomb` in the place that all other fonts have a `dotaccentcomb`. 

I have started looking for this with the (still somewhat sloppy) script `src/00-recursive-scripts-for-robofont/checking-similarity-between-fonts/check-for-specific-components-select_fonts.py`.

So far, I'm not able to pinpoint the issue.

The fuller traceback looks like this:

```
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/recursive/venv/bin/fontmake", line 8, in <module>
    sys.exit(main())
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontmake/__main__.py", line 424, in main
    project.run_from_designspace(designspace_path, **args)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 878, in run_from_designspace
    **kwargs,
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 944, in _run_from_designspace_interpolatable
    designspace, output_path=output_path, output_dir=output_dir, **kwargs
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 299, in build_variable_font
    inplace=True,
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/ufo2ft/__init__.py", line 548, in compileVariableTTF
    ttfDesignSpace, exclude=excludeVariationTables, optimize=optimizeGvar
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 862, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 589, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GSUB', 'GDEF', 'GPOS'])
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 109, in mergeTables
    for m in master_ttfs])
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 97, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 83, in mergeLists
    self.mergeThings(value, values)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 97, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 83, in mergeLists
    self.mergeThings(value, values)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 99, in mergeThings
    assert allEqualTo(out, lst), (out, lst)
AssertionError: (('dotaccentcomb', ('dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'cedillacomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb', 'cedillacomb', 'dotaccentcomb', 'cedillacomb', 'dotaccentcomb', 'cedillacomb', 'dotaccentcomb', 'dotaccentcomb', 'dotaccentcomb')), 'str', '[0]', 'list', '.glyphs', 'Coverage', '[0]', 'list', '.Coverage', 'MarkGlyphSetsDef', '.MarkGlyphSetsDef', 'GDEF', '.table', 'table_G_D_E_F_')
```

**Comment by arrowtype** [comment]
Actually, this may have been a unicodes issue.

After running `src/00-recursive-scripts-for-robofont/clean-up/add-unicodes-from-adobe_glyph_list.py` on all masters, I made it to another error:

`AssertionError: ((3, [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]), 'int', '.FeatureCount', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')`

(This one seems like it's probably about kerning).

**Comment by arrowtype** [comment]
I added blank kerning to mono fonts, and removed a lingering `R.trap` experimental glyph from a source, and ... the variable font built! Awesome.

Next steps:
- Finish refactoring varfontprep, to properly match for a common glyph set
- add alternate diacritics
