### ISSUE TITLE
Make arrows "sharper" and more arrow-like, simplify diagonal arrows

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#318]
Something that has given me low-level anxiety for a while is that the arrows of Recursive feel a bit "softer" than I think they perhaps should. I am also concerned that the horizontal and vertical terminals of diagonal arrows just look a bit odd, reducing the directness of them.

Here's a selection of them, as of v1.040:

![image](https://user-images.githubusercontent.com/45946693/75299878-3c1f0200-5804-11ea-80d5-2546cb8e7bd3.png)

![image](https://user-images.githubusercontent.com/45946693/75299888-43dea680-5804-11ea-97f6-032e38046ab4.png)

![image](https://user-images.githubusercontent.com/45946693/75299901-49d48780-5804-11ea-938b-9802ed59b4ba.png)

![image](https://user-images.githubusercontent.com/45946693/75299911-4e993b80-5804-11ea-9a85-4a2ad25fdb8d.png)

The images above also make me realize that diagonal arrows have mismatching heights.

**Describe the solution you'd like**

I have been testing a route of flipping the sharp points to the outside, and I think this is making them more-instantly read as arrows:

![image](https://user-images.githubusercontent.com/45946693/75300022-a637a700-5804-11ea-95bc-1efd2fdbfd63.png)

![image](https://user-images.githubusercontent.com/45946693/75300257-4c83ac80-5805-11ea-8ad7-ef5216a79f85.png)

Here's a side-by-side comparison of before & after:

![image](https://user-images.githubusercontent.com/45946693/75308127-8fe91580-581b-11ea-9de0-24f501622829.png)

**Process for diagonal arrows**

I have adjusted the `_arrowhead` component to start. This is used directly in `←↑→↓`. For `↖↗↘↙`, espcially in slanted masters, I have had to explore to find a good way to adjust things.

1. Start by copying `arrowup` into `arrowNW`
1. Horizontally flip
1. Rotate by 45 deg

In Slanted Masters, start with `arrowNW`

1. Copy decomposed arrowhead from upright master
2. Rotate by ~~45 deg~~ 31 deg
3. Slant by 5 deg. For Linear styles, copy normal arrowtail and rotate instead to match new angle.
4. clean up corner kinks caused by transformations

Then copy this to `arrowNE`, and:

1. rotate by `-77`
2. clean up corner kinks caused by transformations

**Process for double arrows**

1. copy in `_arrowhead`
2. add a grid of guides (with script) to make it easy to attain symmetrical placement
2. use transforms to squish the arrowhead into place
3. decompose and fix arrowheads if they look overly squished

Next:
- [x] do a pass (maybe with code?) to ensure that all arrow heights match – especially diagonals
- [x] also check that arrowSW and arrowSE are vertically centered
- [x] decompose what is needed for compatibility (glyphs that use components in some masters, but not others: arrowNW, arrowNE, arrowupdown, arrowleftright
- [x] check compatibility with prepolator next
- [x] copy mono to sans
- [x] fix compatbility in `arrowleftright`
- [ ] build!? Solve build issues

to do asap:
- [ ] improve interpolation of `arrowupdown`

**Comment by arrowtype** [comment]
Used:

```
toDecompose = "arrowNW arrowNE arrowupdown arrowleftright".split(" ")

for f in AllFonts():
    for name in toDecompose:
        f[name].decompose()
        print(f"{name} decomposed")
        
```

**Comment by arrowtype** [comment]
- [ ] To complete (later): make the interpolation of `arrowupdown` less kinky. It's bad right now: 

![image](https://user-images.githubusercontent.com/45946693/75412836-c09b7e80-58f1-11ea-9f4d-bc7c61eae535.png)

**Comment by arrowtype** [comment]
Something in my guide-adding scripts is adding anchors into glyphs. -_- I think this may be new RoboFont behavior?

It causes the build to fail like this:

```
Traceback (most recent call last):
  File "build.py", line 70, in <module>
    files = buildFiles(version=version, static=False)
  File "/Users/stephennixon/type-repos/recursive/mastering/build_files.py", line 95, in buildFiles
    makeSources(ds, paths["src"], version)
  File "/Users/stephennixon/type-repos/recursive/mastering/build_files.py", line 72, in makeSources
    prep(os.path.join(src, ds), version)
  File "/Users/stephennixon/type-repos/recursive/mastering/prep_fonts.py", line 518, in prep
    makeCompatible(fonts)
  File "/Users/stephennixon/type-repos/recursive/mastering/prep_fonts.py", line 468, in makeCompatible
    compatibility = glyph.isCompatible(font[glyph.name])
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontParts/base/glyph.py", line 1806, in isCompatible
    return super(BaseGlyph, self).isCompatible(other, BaseGlyph)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontParts/base/base.py", line 659, in isCompatible
    self._isCompatible(other, reporter)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontParts/base/glyph.py", line 1912, in _isCompatible
    missing_from_glyph1.elements()
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

A simple way to fix it is by removing all the anchors in arrows:

```
for f in AllFonts():
	for name in f.keys():
		if "arrow" in name:
			for anchor in f[name].anchors:
				print(anchor)
				print(name)
				print(f.info.styleName)
				f[name].removeAnchor(anchor)
```

However, I should ask on the RF forum why adding guidelines may be causing extra anchors.

**Comment by arrowtype** [comment]
Complete as of b6fbf73a1
